-- AlterTable
ALTER TABLE "Job" ALTER COLUMN "updated_at" DROP DEFAULT;

-- AlterTable
ALTER TABLE "JobTrace" ADD COLUMN     "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "executedBy" SET DATA TYPE TEXT;
